### ISSUE TITLE
Run Time Error 91 - Object Variable Not Set

### ISSUE THREAD

**Issue by KallunWillock** [sancarn/stdVBA-examples#1]
For the most part, the code will run perfectly without incident. Occassionally, however, the code will not run at all - instead, it ends by hitting a runtime error as it's already trying to crash out of the class, but gets caught in the `Class_Terminate` subroutine.

![image](https://user-images.githubusercontent.com/24909875/146500896-5825b62b-ee76-4231-9d2f-3a56d450c7b5.png)

I have found the source of the original problem - incompatible settings on my system for Word. It transpires that neither of the following two lines of code can properly run when the `ActiveWindow` object  is in a maximised state. 
  ```vba
    'Set width and height to that of the frame
    .Width = pWndUserformFrame.Width - 30
    .Height = pWndUserformFrame.Height
```
I will post a proposed solution for your consideration that address thispoint, together a revision to the `Class_Terminate` event to avoid getting caught in a run-time error.

**Comment by sancarn** [comment]
Will be closed in #3
