### ISSUE TITLE
stdChrome CreateFromExisting error

### ISSUE THREAD

**Issue by phobo3s** [sancarn/stdVBA-examples#4]
i can't seem to work the CreateFromExisting method. Since there is no example avaible and the classes is far beyond my comprehension and intelligence i need to ask here. 
i am trying to get the opened chrome instance and use it. 

When i tried the below method i get the: "Runtime error 438. Object doesn't support this property or method." error. 

From here: 
```
'*************************************
'*          EVENT HANDLERS           *
'*************************************
Private Sub Class_Terminate()
        If This.Window.Exists Then Call This.Window.Quit
End Sub   <~~~~~~~it gives error right here
```

My module is here:
```
Sub test2()
    Dim chrome As stdChrome
    Dim hwnd As LongPtr
    Call BringWindowToFront.GetHandleFromPartialCaption(hwnd, "Youtube")
    Dim extWin As stdWindow
    Set extWin = stdWindow.CreateFromHwnd(hwnd)
    Set chrome = stdChrome.CreateFromExisting(extWin.parent)
    With chrome
        Call .Navigate("www.google.com")
        Call .accMain.AwaitForElement(stdLambda.Create("$1.Name like ""Yeniden Yükle"" and $1.Role = ""ROLE_PUSHBUTTON"""))
        Call chrome.accMain.PrintDescTexts("C:\Users\user.name\Desktop\test.txt")
    End With
    Set chrome = Nothing
End Sub
```

**Comment by sancarn** [comment]
Hello, might be worth attaching your excel/word/powerpoint file, because there are other variables in play here. I have used `CreateFromExisting` in my own projects and has been quite effective, never had issues.

Where does it get to in sub `test2`?

**Comment by phobo3s** [comment]
my windows is in Turkish langage, so i get a prolem at this line and changed in Turkish.

`Set .accAddressBar = .accMain.FindFirst(stdLambda.Create("$1.Name like ""Adres ve arama çubuğu"" and $1.Role = ""ROLE_TEXT"""))`

How do i change the code, so if i use "CreateFromExisting" not exit window when the code terminates.

**Comment by sancarn** [comment]
Ah I see the issue now, ok currently you just have to ensure the object doesn't terminate e.g. a module level variable and not setting the object to nothing afterward. But perhaps I should add a `CloseOnInstangeLoss` property

**Comment by phobo3s** [comment]
thank you. And i must say, it has a learning curve of it's own :)

**Comment by sancarn** [comment]
Should be fixed now :) Can supply an additional parameter. `CreateFromExisting` will default to not closing on instance loss.

> it has a learning curve of it's own

It does yeah 😅 Well worth it though 😄
